<?php
/**
 * Novalnet payment extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Novalnet End User License Agreement
 * that is bundled with this package in the file freeware_license_agreement.txt
 *
 * DISCLAIMER
 *
 * If you wish to customize Novalnet payment extension for your needs, please contact technic@novalnet.de for more information.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Copyright (c) 2019 Novalnet AG
 * @license    https://www.novalnet.de/payment-plugins/kostenlos/lizenz
 */
$code = $this->getMethodCode();
$helper = Mage::helper('novalnet_payment');
?>
<ul class="form-list" id="payment_form_<?php echo $this->escapeHtml($code); ?>" style="display:none;">
    <!-- Payment logo -->
    <div>
        <?php if ($this->logoAvailableStatus()): ?>
                <?php
                    $imgpath = $helper->getPaymentLogoUrl() . "banktransfer.png";
                    if ($this->getMethod()->getConfigData('logo')):
                        $imgpath = $helper->getCustomPaymentLogoUrl() . $this->getMethod()->getConfigData('logo');
                    endif;
                ?>
                <img class="nn-logo-img"
                     src="<?php echo $this->escapeHtml($imgpath); ?>"
                     alt="<?php echo $this->escapeHtml($this->getMethod()->getConfigData('title')); ?>"
                     title="<?php echo $this->escapeHtml($this->getMethod()->getConfigData('title')); ?>" />
            </a>
        <?php endif; ?>
    </div>
    <!-- Payment logo -->
    <!-- Payment description -->
    <li>
        <?php
            echo $this->escapeHtml($this->__('Banktransfer payment description'));
        ?>
    </li>
    <!-- Payment description -->
    <!-- Information to the end customer -->
    <?php if ($this->getUserInfo()): ?>
        <li>
            <?php echo $this->escapeHtml($this->getUserInfo()); ?>
        </li>
    <?php endif; ?>
    <!-- Information to the end customer -->
    <!-- Display the payment mode notification -->
    <?php if ($this->getPaymentMode() == FALSE): ?>
        <li>
            <div class="nn-mode">
                <?php
                    echo $this->escapeHtml(
                        $this->__(
                            'Please Note: This transaction will run on TEST MODE and the amount will not be charged'
                        )
                    );
                ?>
            </div>
        </li>
    <?php endif ?>
    <!-- Display the payment mode notification -->
</ul>
