<?php
/**
 * Novalnet payment extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Novalnet End User License Agreement
 * that is bundled with this package in the file freeware_license_agreement.txt
 *
 * DISCLAIMER
 *
 * If you wish to customize Novalnet payment extension for your needs, please contact technic@novalnet.de for more information.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Copyright (c) 2019 Novalnet AG
 * @license    https://www.novalnet.de/payment-plugins/kostenlos/lizenz
 */
$data = $this->getTransactionStatus();
?>

<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><?php echo $this->getHeaderHtml(); ?></td>
            <td class="form-buttons">
                <?php echo $this->getButtonsHtml(); ?>
            </td>
        </tr>
    </table>
</div>
<input type="hidden" name="order_id" value="<?php echo $this->escapeHtml($data->getOrderNo()) ?>"/>

<div class="box-left">
    <!--Novalnet Order Information-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-payment-method">
                <?php echo $this->escapeHtml(Mage::helper('novalnet_payment')->__('Novalnet Order Information')) ?>
            </h4>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label">
                        <label>
                            <?php echo $this->escapeHtml($this->helper('novalnet_payment')->__('Order ID')) ?>
                        </label>
                    </td>
                    <td class="label">
                        <?php
                        $orderViewId = Mage::getModel('sales/order')->loadByIncrementId($data->getOrderId())->getId();
                        $orderViewUrl = Mage::helper('adminhtml')->getUrl(
                            'adminhtml/sales_order/view', array(
                            'order_id' => $orderViewId)
                        );
                        ?>
                        <strong>
                            <a href="<?php echo $this->escapeHtml($orderViewUrl) ?>">
                                <?php echo $this->escapeHtml($data->getOrderId()) ?>
                            </a>
                        </strong>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label>
                            <?php echo $this->escapeHtml($this->helper('novalnet_payment')->__('Store-ID')) ?>
                        </label>
                    </td>
                    <td class="label">
                        <strong><?php echo $this->escapeHtml($data->getStoreId()) ?></strong>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label>
                            <?php echo $this->escapeHtml($this->helper('novalnet_payment')->__('Payment Name')) ?>
                        </label>
                    </td>
                    <td class="label">
                        <strong><?php echo $this->escapeHtml($this->getPaymentTitle()) ?></strong>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label>
                            <?php echo $this->escapeHtml($this->helper('novalnet_payment')->__('Transaction ID')) ?>
                        </label>
                    </td>
                    <td class="label">
                        <strong><?php echo $this->escapeHtml($data->getTransactionNo()) ?></strong>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label>
                            <?php echo $this->escapeHtml($this->helper('novalnet_payment')->__('Transaction-Status')) ?>
                        </label>
                    </td>
                    <td class="label">
                        <strong><?php echo $this->escapeHtml($data->getTransactionStatus()) ?></strong>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label><?php echo $this->escapeHtml($this->helper('novalnet_payment')->__('Amount')) ?></label>
                    </td>
                    <td class="label">
                        <strong>
                            <?php echo $this->escapeHtml(($data->getAmount() / 100) . " " . $this->getCurrencyCode()) ?>
                        </strong>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>
<div class="box-right">
    <!--Novalnet Order Shop Information-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-payment-method">
                <?php echo $this->escapeHtml(Mage::helper('novalnet_payment')->__('Novalnet Shop Information')) ?>
            </h4>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list" width="100%">
                <?php if ($data->getShopUrl()) : ?>
                    <tr>
                        <td class="label">
                            <label>
                                <?php echo $this->escapeHtml($this->helper('novalnet_payment')->__('Shop URL')) ?>
                            </label>
                        </td>
                        <td style="word-break:break-word;">
                            <strong><?php echo $this->escapeHtml($data->getShopUrl()) ?></strong>
                        </td>
                    </tr>
                <?php endif; ?>
            </table>
        </div>
    </div>
</div>

<div class="box-right">
    <!--Novalnet Order Additional Information-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-payment-method">
                <?php echo $this->escapeHtml(Mage::helper('novalnet_payment')->__('Novalnet Additional Information')) ?>
            </h4>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label">
                        <label>
                            <?php echo $this->escapeHtml($this->helper('novalnet_payment')->__('Remote Ip')) ?>
                        </label>
                    </td>
                    <td class="label">
                        <strong><?php echo $this->escapeHtml($data->getRemoteIp()) ?></strong>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label>
                            <?php echo $this->escapeHtml($this->helper('novalnet_payment')->__('Customer-ID')) ?>
                        </label>
                    </td>
                    <td class="label">
                        <strong><?php echo $this->escapeHtml($data->getCustomerId()) ?></strong>
                    </td>
                </tr>
                <?php if ($data->getNcNo()) : ?>
                    <tr>
                        <td class="label">
                            <label>
                                <?php echo $this->escapeHtml($this->helper('novalnet_payment')->__('NC No')) ?>
                            </label>
                        </td>
                        <td class="label">
                            <strong><?php echo $this->escapeHtml($data->getNcNo()) ?></strong>
                        </td>
                    </tr>
                <?php endif; ?>
            </table>
        </div>
    </div>
</div>
