<?php
/**
 * Novalnet payment extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Novalnet End User License Agreement
 * that is bundled with this package in the file freeware_license_agreement.txt
 *
 * DISCLAIMER
 *
 * If you wish to customize Novalnet payment extension for your needs, please contact technic@novalnet.de for more information.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Copyright (c) 2019 Novalnet AG
 * @license    https://www.novalnet.de/payment-plugins/kostenlos/lizenz
 */
$helper = Mage::helper('novalnet_payment');
$data = $this->getTransactionTraces();
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><?php echo $this->getHeaderHtml(); ?></td>
            <td class="form-buttons">
                <?php echo $this->getButtonsHtml(); ?>
            </td>
        </tr>
    </table>
</div>
<input type="hidden" name="order_id" value="<?php echo $this->escapeHtml($data->getOrderId()) ?>"/>
<div class="box-left">
    <!--Novalnet Order Information-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-payment-method">
                <?php echo $this->escapeHtml($helper->__('Novalnet Order Information')) ?>
            </h4>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label">
                        <label><?php echo $this->escapeHtml($helper->__('Order-ID')) ?></label>
                    </td>
                    <td class="label">
                        <?php
                        $orderViewId = Mage::getModel('sales/order')->loadByIncrementId($data->getOrderId())->getId();
                        $orderViewUrl = Mage::helper('adminhtml')->getUrl(
                            'adminhtml/sales_order/view', array(
                            'order_id' => $orderViewId)
                        );
                        ?>
                        <strong>
                            <a href="<?php echo $this->escapeHtml($orderViewUrl) ?>">
                                <?php echo $this->escapeHtml($data->getOrderId()) ?>
                            </a>
                        </strong>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label><?php echo $this->escapeHtml($helper->__('Store-ID')) ?></label>
                    </td>
                    <td class="label">
                        <strong><?php echo $this->escapeHtml($data->getStoreId()) ?></strong>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label><?php echo $this->escapeHtml($helper->__('Transaction-ID')) ?></label>
                    </td>
                    <td class="label">
                        <strong><?php echo $this->escapeHtml($data->getTransactionId()) ?></strong>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label><?php echo $this->escapeHtml($helper->__('Payment Name')) ?></label>
                    </td>
                    <td class="label">
                        <strong><?php echo $this->escapeHtml($this->getPaymentTitle()) ?></strong>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>


<div class="box-right">
    <!--Novalnet Order Shop Information-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-payment-method">
                <?php echo $this->escapeHtml($helper->__('Novalnet Shop Information')) ?>
            </h4>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list" width="100%">
                <tr>
                    <td class="label">
                        <label><?php echo $this->escapeHtml($helper->__('Shop URL')) ?></label>
                    </td>
                    <td style="word-break:break-word;">
                        <strong><?php echo $this->escapeHtml($data->getShopUrl()) ?></strong>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>

<div class="box-right">
    <!--Novalnet Order Additional Information-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-payment-method">
                <?php echo $this->escapeHtml($helper->__('Novalnet Additional Information')) ?>
            </h4>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label">
                        <label><?php echo $this->escapeHtml($helper->__('Customer-ID')) ?></label>
                    </td>
                    <td class="label">
                        <strong><?php echo $this->escapeHtml($data->getCustomerId()) ?></strong>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>
<!-- Novalnet API Data -->
<div class="box-left" style="clear:both;">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-payment-method">
                <?php echo $this->escapeHtml($helper->__('Novalnet Request Data')) ?>
            </h4>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list" width="100%">
                <tr>
                    <td class="label">
                        <label><?php echo $this->escapeHtml($helper->__('Request Data')) ?></label><br />
                        <div style="height:250px;overflow:scroll;width:600px;"><strong><?php
                                $request = $data->getRequestData();
                                $isSerialized = $helper->is_serialized($request);
                                $getrequestData = ($isSerialized === true) ? unserialize($request) :
                                unserialize(base64_decode($request));
                                echo "<pre>";
                                print_r($getrequestData);
                                echo "</pre>";
                                ?></strong>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>

<div class="box-right">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-payment-method">
                <?php echo $this->escapeHtml($helper->__('Novalnet Response Data')) ?>
            </h4>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list" width="100%">
                <tr>
                    <td class="label">
                        <label><?php echo $this->escapeHtml($helper->__('Response Data')) ?></label><br />
                        <div style="height:250px;overflow:scroll;width:600px;"><strong><?php
                                $response = $data->getResponseData();
                                $isSerialized = $helper->is_serialized($response);
                                $getresponseData = ($isSerialized === true) ? unserialize($response) :
                                unserialize(base64_decode($response));
                                echo "<pre>";
                                print_r($getresponseData);
                                echo "</pre>";
                                ?></strong>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>
