<?php
/**
 * Novalnet payment extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Novalnet End User License Agreement
 * that is bundled with this package in the file freeware_license_agreement.txt
 *
 * DISCLAIMER
 *
 * If you wish to customize Novalnet payment extension for your needs, please contact technic@novalnet.de for more information.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Copyright (c) 2019 Novalnet AG
 * @license    https://www.novalnet.de/payment-plugins/kostenlos/lizenz
 */
$code = $this->getMethodCode();
$helper = Mage::helper('novalnet_payment');

$vendorId = Mage::getStoreConfig('novalnet_global/novalnet/merchant_id');
$productId = Mage::getStoreConfig('novalnet_global/novalnet/product_id');
$currentLanguage = explode("_", Mage::app()->getLocale()->getLocaleCode());
$encodedkey = base64_encode('vendor=' . $vendorId . '&product=' . $productId . '&server_ip=' . $helper->getServerAddr(). '&lang=' . $currentLanguage[0]);
$nnIframeSource = 'https://secure.novalnet.de/cc?api=' . $encodedkey;
?>

<ul class="form-list" id="payment_form_<?php echo $this->escapeHtml($code); ?>" style="display:none;">
    <!-- Credit Card payment logo -->
    <div>
        <?php if ($this->logoAvailableStatus()): ?>
                <?php if($this->getMethod()->getConfigData('logo')): ?>
                    <?php $imgpath = $helper->getCustomPaymentLogoUrl() . $this->getMethod()->getConfigData('logo'); ?>
                    <img class="nn-logo-img"
                         src="<?php echo $this->escapeHtml($imgpath); ?>"
                         alt="<?php echo $this->escapeHtml($this->getMethod()->getConfigData('title')); ?>"
                         title="<?php echo $this->escapeHtml($this->getMethod()->getConfigData('title')); ?>" />
                <?php else: ?>
                    <?php foreach ($this->getCcAvailableTypes() as $typeCode => $typeName): ?>
                        <?php $imgpath = $helper->getPaymentLogoUrl() . $typeCode . ".png"; ?>
                        <img class="nn-logo-img"
                             src="<?php echo $this->escapeHtml($imgpath); ?>"
                             alt="<?php echo $this->escapeHtml($this->getMethod()->getConfigData('title')); ?>"
                             title="<?php echo $this->escapeHtml($this->getMethod()->getConfigData('title')); ?>" />
                    <?php endforeach; ?>
                <?php endif; ?>
            </a>
        <?php endif; ?>
    </div>
    <!-- Credit Card payment logo -->
    <div class="nn-loader"
         id='cc_loading'
         style="background: url('<?php echo $this->escapeHtml($helper->getPaymentLogoUrl()); ?>novalnet-loading-icon.gif')
         50% 50% no-repeat;"></div>
    <!-- Payment description -->
    <li>
        <?php
        echo $this->escapeHtml(
            $this->__('The amount will be debited from your credit/debit card')
        );
        ?>
    </li>
    <!-- Payment description -->
    <!-- Information to the end customer -->
    <?php if ($this->getUserInfo()): ?>
        <li>
            <?php echo $this->escapeHtml($this->getUserInfo()); ?>
        </li>
    <?php endif; ?>
    <!-- Information to the end customer -->
    <!-- Display the payment mode notification -->
    <?php if ($this->getPaymentMode() == false): ?>
        <li>
            <div class="nn-mode">
                <?php
                echo $this->escapeHtml(
                    $this->__('Please Note: This transaction will run on TEST MODE and the amount will not be charged')
                );
                ?>
            </div>
        </li>
    <?php endif; ?>
    <!-- Display the payment mode notification -->
    <!-- Credit Card Iframe form -->
    <div id="cc_oneclick_new">
        <iframe
            id="novalnet_iframe"
            scrolling="no"
            src="<?php echo $this->escapeHtml($nnIframeSource); ?>"
            width='100%'
            style="border:none !important;"
            onload="initIframe()">
        </iframe>
    </div>
    <!-- Credit Card Iframe form -->
    <!-- Form hidden elements -->
    <input type="hidden" id="cc_oneclick_shopping" name="cc_oneclick_shopping" value="" />
    <input type="hidden" id="cc_enter_data" name="cc_enter_data" value="1" />
    <input type="hidden" id="nn_is_admin" name="nn_is_admin" value="1"/>
    <input type="hidden" id="nn_pan_hash" name="nn_pan_hash"/>
    <input type="hidden" id="nn_cc_uniqueid" name="nn_cc_uniqueid"/>
    <input type="hidden" id="nn_chk_button" name="nn_chk_button"/>
    <input type="hidden" id="nn_cc_do_redirect" name="nn_cc_do_redirect"/>
    <input type="hidden"
           id="nn_cc_req_obj"
           value="<?php echo $this->escapeHtml($this->getCcRequestObj()); ?>" />
    <input type="hidden"
           id="nn_client_key"
           value="<?php echo $this->escapeHtml($this->getClientKey()); ?>" />
    <input type="hidden"
           id="nn_cc_layout"
           value="<?php echo $this->escapeHtml($this->getCcFormLayout()); ?>" />
    <input type="hidden"
           id="nn_cc_holder_label_css"
           value="<?php echo $this->escapeHtml($this->getStyleConfig('card_holder_label_css')); ?>" />
    <input type="hidden"
           id="nn_cc_holder_field_css"
           value="<?php echo $this->escapeHtml($this->getStyleConfig('card_holder_field_css')); ?>" />
    <input type="hidden"
           id="nn_cc_number_label_css"
           value="<?php echo $this->escapeHtml($this->getStyleConfig('card_number_label_css')); ?>" />
    <input type="hidden"
           id="nn_cc_number_field_css"
           value="<?php echo $this->escapeHtml($this->getStyleConfig('card_number_field_css')); ?>" />
    <input type="hidden"
           id="nn_cc_date_label_css"
           value="<?php echo $this->escapeHtml($this->getStyleConfig('card_date_label_css')); ?>" />
    <input type="hidden"
           id="nn_cc_date_field_css"
           value="<?php echo $this->escapeHtml($this->getStyleConfig('card_date_field_css')); ?>" />
    <input type="hidden"
           id="nn_cc_cvc_label_css"
           value="<?php echo $this->escapeHtml($this->getStyleConfig('card_cvc_label_css')); ?>" />
    <input type="hidden"
           id="nn_cc_cvc_field_css"
           value="<?php echo $this->escapeHtml($this->getStyleConfig('card_cvc_field_css')); ?>" />    
    <input type="hidden"
           id="nn_cc_standard_style_label"
           value="<?php echo $this->escapeHtml($this->getStyleConfig('standard_style_label')); ?>" />
    <input type="hidden"
           id="nn_cc_standard_style_input"
           value="<?php echo $this->escapeHtml($this->getStyleConfig('standard_style_input')); ?>" />
    <input type="hidden"
           id="nn_cc_standard_style_css"
           value="<?php echo $this->escapeHtml($this->getStyleConfig('standard_style_css')); ?>" />
    <input type="hidden"
           id="nn_cc_validate_text"
           value="<?php echo $this->escapeHtml($this->__('Your credit card details are invalid')); ?>" />
    <input type="hidden" id="nn_cc_holder_label" value="<?php echo $this->escapeHtml($this->__('Card holder name')); ?>" />
    <input type="hidden" id="nn_cc_holder_field" value="<?php echo $this->escapeHtml($this->__('Name on card')); ?>" />
    <input type="hidden" id="nn_cc_number_label" value="<?php echo $this->escapeHtml($this->__('Card number')); ?>" />
    <input type="hidden" id="nn_cc_number_field" value="<?php echo $this->escapeHtml($this->__('XXXX XXXX XXXX XXXX')); ?>" />
    <input type="hidden" id="nn_cc_date_label" value="<?php echo $this->escapeHtml($this->__('Expiry date')); ?>" />
    <input type="hidden" id="nn_cc_date_field" value="<?php echo $this->escapeHtml($this->__('MM / YYYY')); ?>" />
    <input type="hidden" id="nn_cc_cvc_label" value="<?php echo $this->escapeHtml($this->__('CVC/CVV/CID')); ?>" />
    <input type="hidden" id="nn_cc_cvc_field" value="<?php echo $this->escapeHtml($this->__('XXX')); ?>" />
    <input type="hidden" id="nn_cc_cvc_hint" value="<?php echo $this->escapeHtml($this->__('what is this?')); ?>" />
    <!-- Form hidden elements -->
</ul>
