<?php
/**
 * Novalnet payment extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Novalnet End User License Agreement
 * that is bundled with this package in the file freeware_license_agreement.txt
 *
 * DISCLAIMER
 *
 * If you wish to customize Novalnet payment extension for your needs, please contact technic@novalnet.de for more information.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Copyright (c) 2019 Novalnet AG
 * @license    https://www.novalnet.de/payment-plugins/kostenlos/lizenz
 */
$code = $this->getMethodCode();
$helper = Mage::helper('novalnet_payment');
$config = $helper->getModel('Service_Abstract');
$billingInfo = $this->getBillingInfo();
$customerSession = $helper->getAdminCheckoutSession();
$dateOfBirth = ($customerSession->getCustomer()->hasDob() ? $customerSession->getCustomer()->getDob() : '');
$dateOfBirth = $dateOfBirth ? Mage::getSingleton('core/date')->gmtDate('Y-m-d', $dateOfBirth) : '';
$company = $helper->getEndUserCompany();
$orderTotal = $helper->getCheckout()->getQuote()->getGrandTotal();
$priceHelper = Mage::helper('core');
$formattedPrice = $priceHelper->currency($orderTotal, true, false);
$instalmentPeriods = array();
$allcycles = explode(',', $this->getInstalmentTotal());
foreach($allcycles as $allcycle) {
    if (($orderTotal / $allcycle) >= 9.99) {
        $instalmentPeriods[$allcycle] = ($this->getInstalmentCycle() == 1)
            ? $allcycle . __(' Cycles / ') . $priceHelper->currency($orderTotal / $allcycle, true, false) . __(' Every month', $this->getInstalmentCycle())
            : $allcycle . __(' Cycles / ') . $priceHelper->currency($orderTotal / $allcycle, true, false) . __(' Every %s months', $this->getInstalmentCycle());
    }
}
?>

<ul class="form-list" id="payment_form_<?php echo $this->escapeHtml($code); ?>" style="display:none;">
    <!-- Direct Debit SEPA Instalment payment logo -->
    <div>
        <?php if ($this->logoAvailableStatus()): ?>
                <?php
                    $imgpath = $helper->getPaymentLogoUrl() . "sepainstalment.png";
                    if ($this->getMethod()->getConfigData('logo')):
                        $imgpath = $helper->getCustomPaymentLogoUrl() . $this->getMethod()->getConfigData('logo');
                    endif;
                ?>
                <img class="nn-logo-img"
                     src="<?php echo $this->escapeHtml($imgpath); ?>"
                     alt="<?php echo $this->escapeHtml($this->getMethod()->getConfigData('title')); ?>"
                     title="<?php echo $this->escapeHtml($this->getMethod()->getConfigData('title')); ?>" />
            </a>
        <?php endif; ?>
    </div>
    <!-- Direct Debit SEPA Instalment payment logo -->
    <div class="nn-loader"
         id='sepa_loading'
         style="background: url('<?php echo $this->escapeHtml($helper->getPaymentLogoUrl()); ?>novalnet-loading-icon.gif')
         50% 50% no-repeat;">
    </div>
    <!-- Payment description -->
    <li>
        <?php echo $this->escapeHtml($this->__('The amount will be debited from your account by Novalnet')); ?>
    </li>
    <!-- Payment description -->
    <!-- Information to the end customer -->
    <?php if ($this->getUserInfo()): ?>
        <li>
            <?php echo $this->escapeHtml($this->getUserInfo()); ?>
        </li>
    <?php endif; ?>
    <!-- Information to the end customer -->
    <!-- Display the payment mode notification -->
    <?php if ($this->getPaymentMode() == FALSE): ?>
        <li>
            <div class="nn-mode">
                <?php
                echo $this->escapeHtml(
                    $this->__(
                        'Please Note: This transaction will run on TEST MODE and the amount will not be charged'
                    )
                );
                ?>
            </div>
        </li>
    <?php endif; ?>
    <!-- Display the payment mode notification -->
    <!-- Direct Debit SEPA Instalment local form -->
    <div id="sepa_instalment_local_form">
        <li>
            <label style="float:none;" for="<?php echo $this->escapeHtml($code) ?>_account_holder">
                <?php echo $this->escapeHtml($this->__('Account Holder')) ?><span class="required"> *</span>
            </label><br/>
            <div class="input-box">
                <input type="text"
                       title="<?php echo $this->escapeHtml($this->__('Account Holder')) ?>"
                       class="required-entry input-text"
                       id="<?php echo $this->escapeHtml($code) ?>_account_holder"
                       onkeypress="return sepaInstalmentFormValidate(event)"
                       name="<?php echo $this->escapeHtml($code) ?>_account_holder"
                       autocomplete="off"
                       value="<?php echo $this->escapeHtml(
                           $billingInfo->getFirstname() . ' ' . $billingInfo->getLastname()
                       ); ?>" />
            </div>
        </li>
        <li>
            <label style="float:none;" for="<?php echo $this->escapeHtml($code) ?>_account_number">
                <?php echo $this->escapeHtml($this->__('IBAN')) ?><span class="required"> *</span>
            </label><br/>
            <div class="input-box">
                <input type="text"
                       id="<?php echo $this->escapeHtml($code) ?>_account_number"
                       name="<?php echo $this->escapeHtml($code); ?>_account_number"
                       onkeypress = "return NovalnetUtility.formatIban(event)"
                       onchange = "return NovalnetUtility.formatIban(event)"
                       title="<?php echo $this->escapeHtml($this->__('IBAN')) ?>"
                       class="required-entry input-text"
                       autocomplete="off"
                       value="" />
            </div>
        </li>
        <li class="fields">
            <div class="form-group">
                <a id = "sepa_instalment_mandate_toggle" style = "cursor:pointer;" class="resp-accordion"><strong><strong><?php echo $this->escapeHtml($this->__('I hereby grant the mandate for the SEPA direct debit')) ?></strong> <?php echo $this->escapeHtml($this->__('(electronic transmission)')) ?> <strong><?php echo $this->escapeHtml($this->__('and confirm that the given bank details are correct!')) ?></strong></strong></a>
            <div class="resp-accordion" id="sepa_instalment_mandate_details" style="display:none; padding:5px; border: 1px solid; border-color: #ddd;">
              <?php echo $this->escapeHtml($this->__('I authorise (A) Novalnet AG to send instructions to my bank to debit my account and (B) my bank to debit my account in accordance with the instructions from Novalnet AG.')) ?>
              <br>
              <br>
              <strong><?php echo $this->escapeHtml($this->__('Creditor identifier: DE53ZZZ00000004253')) ?></strong>
              <br>
              <br>
              <strong><?php echo $this->escapeHtml($this->__('Note:')) ?></strong> <?php echo $this->escapeHtml($this->__('You are entitled to a refund from your bank under the terms and conditions of your agreement with bank. A refund must be claimed within 8 weeks starting from the date on which your account was debited.')) ?>
            </div>
        </li>
        <!-- DOB for Direct Debit SEPA Instalment payment guarantee -->
        <?php if (!$company): ?>
            <li>
                <label for="<?php echo $this->escapeHtml($code) ?>_dob">
                    <?php echo $this->escapeHtml($this->__('Date Of Birth')) ?><span class="required"> *</span>
                </label><br/>
                <div class="input-box">
                    <input type="text"
                           autocomplete="off"
                           id="<?php echo $this->escapeHtml($code); ?>_dob"
                           name="payment[dob_date]"
                           maxlength="2"
                           title="<?php echo $this->escapeHtml($this->__('DATE')); ?>"
                           class="input-text required-entry validate-novalnet-date minimum-length-2"
                           value="<?php echo $this->escapeHtml($dateOfBirth); ?>"
                           placeholder="<?php echo $this->escapeHtml($this->__('DD')); ?>"/>
                    <input type="text"
                           autocomplete="off"
                           id="<?php echo $this->escapeHtml($code); ?>_dob"
                           name="payment[dob_month]"
                           maxlength="2"
                           title="<?php echo $this->escapeHtml($this->__('MONTH')); ?>"
                           class="input-text required-entry validate-novalnet-month minimum-length-2"
                           value="<?php echo $this->escapeHtml($dateOfBirth); ?>"
                           placeholder="<?php echo $this->escapeHtml($this->__('MM')); ?>"/>
                    <span class="autocomplete">
                        <input type="text"
                               autocomplete="off"
                               id="<?php echo $this->escapeHtml($code); ?>_dob"
                               name="payment[dob_year]"
                               maxlength="4"
                               onkeypress="autoCompleteYear(this)"
                               title="<?php echo $this->escapeHtml($this->__('YEAR')); ?>"
                               class="input-text required-entry validate-novalnet-year minimum-length-4"
                               value="<?php echo $this->escapeHtml($dateOfBirth); ?>"
                               placeholder="<?php echo $this->escapeHtml($this->__('YYYY')); ?>"/>
                     </span>
                </div>
            </li>
        <?php endif ?>
        <!-- DOB for Direct Debit SEPA Instalment payment guarantee -->

    <div class="nn-payment-instalment">
        <h3><?php echo $this->escapeHtml(__('Choose your instalment plan')); ?></h3>
        <p><?php echo $this->escapeHtml(__('Choose the financing option that best fits your needs and you will be charged based on that chosen plan')); ?></p>
        <div class="control">
            <strong>
                <p>
                    <span><?php echo $this->escapeHtml(__('Net loan amount: ')); ?></span>
                    <span class="price"><?php echo $formattedPrice; ?></span>
                </p>
            </strong>
            <select id="<?php /* @noEscape */ echo $code; ?>_instalment_period" name="novalnet_sepa_instalment_period"
                    class="select required-entry validate-select">
                <?php foreach ($instalmentPeriods as $instalmentKey => $instalmentValue) : ?>
                    <option value="<?php echo $instalmentKey; ?>">
                        <?php echo $instalmentValue; ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>

    </div>
    <!-- Direct Debit Instalment SEPA local form -->
    <!-- Form hidden elements -->
    <input id="nnSepaInstalment_new_form" name="nnSepaInstalment_new_form" type="hidden" value="" />
    <!-- Form hidden elements -->
</ul>
<script type="text/javascript">
    Translator.add(
        'Please enter valid birthdate',
        '<?php echo $this->__('Please enter valid birthdate'); ?>'
    );

    Translator.add(
        'Your account details are invalid',
        '<?php echo $this->__('Your account details are invalid') . '!'; ?>'
    );
</script>
