<?php
/**
 * Novalnet payment extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Novalnet End User License Agreement
 * that is bundled with this package in the file freeware_license_agreement.txt
 *
 * DISCLAIMER
 *
 * If you wish to customize Novalnet payment extension for your needs, please contact technic@novalnet.de for more information.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Copyright (c) 2019 Novalnet AG
 * @license    https://www.novalnet.de/payment-plugins/kostenlos/lizenz
 */
$helper = Mage::helper('novalnet_payment');
$tracesCollection = $this->getTransactionTraces();
$i = 1;
foreach ($tracesCollection as $transactioOverviewId => $data) {
    ?>
    <?php if ($i == 1): ?>
        <div class="box-left">
            <!--Novalnet Order Information-->
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-payment-method">
                        <?php echo $this->escapeHtml($helper->__('Novalnet Order Information')) ?>
                    </h4>
                </div>
                <div class="fieldset">
                    <table cellspacing="0" class="form-list">
                        <tr>
                            <td class="label">
                                <label><?php echo $this->escapeHtml($helper->__('Store-ID')) ?></label>
                            </td>
                            <td class="label">
                                <strong><?php echo $this->escapeHtml($data->getStoreId()) ?></strong>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <label><?php echo $this->escapeHtml($helper->__('Order-ID')) ?></label>
                            </td>
                            <td class="label">
                                <strong><?php echo $this->escapeHtml($data->getOrderId()) ?></strong>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>

        <div class="box-right">
            <!--Novalnet Order Information-->
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-payment-method">
                        <?php echo $this->escapeHtml($helper->__('Novalnet Additional Information')) ?>
                    </h4>
                </div>
                <div class="fieldset">
                    <table cellspacing="0" class="form-list">
                        <tr>
                            <td class="label">
                                <label><?php echo $this->escapeHtml($helper->__('Customer-ID')) ?></label>
                            </td>
                            <td class="label">
                                <strong><?php echo $this->escapeHtml($data->getCustomerId()) ?></strong>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <label><?php echo $this->escapeHtml($helper->__('Shop URL')) ?></label>
                            </td>
                            <td style="word-break:break-word;">
                                <strong><?php echo $this->escapeHtml($data->getShopUrl()) ?></strong>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <?php
    endif;
    $i++;
    ?>

    <!-- Novalnet API Data -->
    <div class="box-left" style="clear:both;">
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-payment-method" style="float:none;">
                    <?php echo $this->escapeHtml($helper->__('Novalnet Request Data')) ?>
                    <span style="float:right;">
                        <?php echo 'TID : ' . $this->escapeHtml($data->getTransactionId()) ?>
                    </span>
                </h4>
            </div>
            <div class="fieldset">
                <table cellspacing="0" class="form-list" width="100%">
                    <tr>
                        <td class="label">
                            <label><?php echo $this->escapeHtml($helper->__('Request Data')) ?></label><br/>
                            <?php
                            $request = $data->getRequestData();
                            $isSerialized = $helper->is_serialized($request);
                            $getrequestData = ($isSerialized === true) ? unserialize($request) :
                            unserialize(base64_decode($request));
                            if ($getrequestData) {
                                ?>
                                <div style="height:250px;overflow:scroll;width:470px;">
                                    <strong> <?php
                                        echo "<pre>";
                                        print_r($getrequestData);
                                        echo "</pre>";
                                        ?> </strong>
                                </div>
                            <?php } ?>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>

    <div class="box-right">
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-payment-method" style="float:none;">
                    <?php echo $this->escapeHtml($helper->__('Novalnet Response Data')) ?>
                    <span style="float:right;">
                        <?php echo 'TID : ' . $this->escapeHtml($data->getTransactionId()) ?>
                    </span>
                </h4>
            </div>
            <div class="fieldset">
                <table cellspacing="0" class="form-list" width="100%">
                    <tr>
                        <td class="label">
                            <label><?php echo $this->escapeHtml($helper->__('Response Data')) ?></label><br />
                            <?php
                            $response = $data->getResponseData();
                            $isSerialized = $helper->is_serialized($response);
                            $getresponseData = ($isSerialized === true) ? unserialize($response) :
                            unserialize(base64_decode($response));
                            if ($getresponseData) {
                                ?>
                                <div style="height:250px;overflow:scroll;width:470px;">
                                    <strong> <?php
                                        echo "<pre>";
                                        print_r($getresponseData);
                                        echo "</pre>";
                                        ?> </strong>
                                </div>
                            <?php } ?>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
<?php } ?>
